name: resolvehub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  # Firebase dependencies (updated to compatible versions)
  firebase_core: ^3.8.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.2.0
  google_fonts: ^3.0.1

  # UI-related packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  fluttertoast: ^8.0.0

  # Navigation & routing
  go_router: ^9.0.0

  # Form validation
  flutter_form_builder: ^7.0.0

  # Optional: Image picker for uploading user profile images
  image_picker: ^1.1.2

  # Optional: For file management
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

